export const ACTIONS = {
    COMPTEUR: {
        INCREMENTER: 'ACTION_COMPTEUR_INCREMENTER',
        DECREMENTER: 'ACTION_COMPTEUR_DECREMENTER',
        EFFACER: 'ACTION_COMPTEUR_EFFACER',
        COULEUR: 'ACTION_COMPTEUR_COULEUR',
        AFFICHER: 'ACTION_COMPTEUR_AFFICHER'
    },
    CITATION: {
        PLATON: 'CITATION_PLATON',
        JUNG: 'CITATION_JUNG',
        SPINOZA: 'CITATION_SPINOZA',
        ALEATOIRE: {
            DALAI_LAMA: 'CITATION_ALEATOIRE_DALAI_LAMA',
            GANDHI: 'CITATION_ALEATOIRE_GANDHI',
            COLUCHE: 'CITATION_ALEATOIRE_COLUCHE'
        },
        EFFACER: 'CITATION_EFFACER'
    },
    RESTAURANT: {
        ADD: 'RESTAURANT_ADD',
        JOYEUX_SERIAL_KILLER: 'RESTAURANT_JOYEUX_SERIAL_KILLER',
        EFFACER: 'RESTAURANT_EFFACER'
    }
};
